BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Parent] ALTER COLUMN [email] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Parent] ADD [isGuest] BIT NOT NULL CONSTRAINT [Parent_isGuest_df] DEFAULT 1;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
