BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Story] ADD [videoSourceType] NVARCHAR(1000) NOT NULL CONSTRAINT [Story_videoSourceType_df] DEFAULT 'UPLOAD', [youtubeId] NVARCHAR(1000);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
